[2018-12-06 02:25:34] requirements_debian_update_system
requirements_debian_update_system () 
{ 
    __rvm_try_sudo apt-get --quiet --yes update || { 
        \typeset __ret=$?;
        case ${__ret} in 
            100)
                rvm_error "There has been an error while updating your system using \`apt-get\`.
It seems that there are some 404 Not Found errors for repositories listed in:

    /etc/apt/sources.list
    /etc/apt/sources.list.d/*.list

Make sure that all repositories are available from your system and verify your setup by running manually:

    sudo apt-get update

Make sure that it works correctly before proceeding with RVM.

If you are working from the GUI instead of the terminal, you might want to verify and fix broken
repositories using \"Software & Updates\" application.
"
            ;;
        esac;
        return ${__ret}
    }
}
current path: /home/sec/.rvm/src/rvm
PATH=/opt/anaconda3/bin:/home/sec/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/sec/.dotnet/tools:/home/sec/.rvm/bin
command(2): requirements_debian_update_system ruby-2.5.1
++ /scripts/functions/requirements/debian : requirements_debian_update_system()  46 > __rvm_try_sudo apt-get --quiet --yes update
++ /scripts/functions/utility : __rvm_try_sudo()  367 > typeset -a command_to_run
++ /scripts/functions/utility : __rvm_try_sudo()  368 > typeset sudo_path sbin_path missing_paths
++ /scripts/functions/utility : __rvm_try_sudo()  369 > command_to_run=("$@")
++ /scripts/functions/utility : __rvm_try_sudo()  370 > ((  UID == 0  ))
++ /scripts/functions/utility : __rvm_try_sudo()  371 > case "$rvm_autolibs_flag_number" in
++ /scripts/functions/utility : __rvm_try_sudo()  386 > is_a_function __rvm_sudo
++ /scripts/functions/support : is_a_function()  5 > typeset -f __rvm_sudo
++ /scripts/functions/utility : __rvm_try_sudo()  388 > missing_paths=
++ /scripts/functions/utility : __rvm_try_sudo()  389 > for sbin_path in /sbin /usr/sbin /usr/local/sbin
++ /scripts/functions/utility : __rvm_try_sudo()  391 > [[ -d /sbin ]]
++ /scripts/functions/utility : __rvm_try_sudo()  391 > [[ :/opt/anaconda3/bin:/home/sec/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/sec/.dotnet/tools:/home/sec/.rvm/bin: != *\:\/\s\b\i\n\:* ]]
++ /scripts/functions/utility : __rvm_try_sudo()  389 > for sbin_path in /sbin /usr/sbin /usr/local/sbin
++ /scripts/functions/utility : __rvm_try_sudo()  391 > [[ -d /usr/sbin ]]
++ /scripts/functions/utility : __rvm_try_sudo()  391 > [[ :/opt/anaconda3/bin:/home/sec/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/sec/.dotnet/tools:/home/sec/.rvm/bin: != *\:\/\u\s\r\/\s\b\i\n\:* ]]
++ /scripts/functions/utility : __rvm_try_sudo()  389 > for sbin_path in /sbin /usr/sbin /usr/local/sbin
++ /scripts/functions/utility : __rvm_try_sudo()  391 > [[ -d /usr/local/sbin ]]
++ /scripts/functions/utility : __rvm_try_sudo()  391 > [[ :/opt/anaconda3/bin:/home/sec/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/sec/.dotnet/tools:/home/sec/.rvm/bin: != *\:\/\u\s\r\/\l\o\c\a\l\/\s\b\i\n\:* ]]
++ /scripts/functions/utility : __rvm_try_sudo()  395 > [[ -n '' ]]
++ /scripts/functions/utility : __rvm_try_sudo()  398 > command_to_run=(__rvm_sudo -p "%p password required for '$*': " "${command_to_run[@]}")
++ /scripts/functions/utility : __rvm_try_sudo()  405 > __rvm_sudo -p '%p password required for '\''apt-get --quiet --yes update'\'': ' apt-get --quiet --yes update
++ /scripts/functions/support : __rvm_sudo()  357 > command sudo -p '%p password required for '\''apt-get --quiet --yes update'\'': ' apt-get --quiet --yes update
++ /scripts/functions/support : __rvm_sudo()  357 > sudo -p '%p password required for '\''apt-get --quiet --yes update'\'': ' apt-get --quiet --yes update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 https://download.mono-project.com/repo/ubuntu vs-bionic InRelease
Hit:3 http://dl.google.com/linux/chrome/deb stable Release
Hit:4 http://linux.teamviewer.com/deb stable InRelease
Hit:5 http://security.ubuntu.com/ubuntu cosmic-security InRelease
Hit:6 http://id.archive.ubuntu.com/ubuntu cosmic InRelease
Hit:8 http://packages.microsoft.com/repos/vscode stable InRelease
Hit:9 http://id.archive.ubuntu.com/ubuntu cosmic-updates InRelease
Hit:10 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Hit:11 http://id.archive.ubuntu.com/ubuntu cosmic-backports InRelease
Hit:12 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu cosmic InRelease
Ign:13 http://ppa.launchpad.net/no1wantdthisname/ppa/ubuntu cosmic InRelease
Err:14 http://ppa.launchpad.net/no1wantdthisname/ppa/ubuntu cosmic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists...
E: The repository 'http://ppa.launchpad.net/no1wantdthisname/ppa/ubuntu cosmic Release' does not have a Release file.
++ /scripts/functions/utility : __rvm_try_sudo()  405 > return 100
++ /scripts/functions/requirements/debian : requirements_debian_update_system()  48 > typeset __ret=100
++ /scripts/functions/requirements/debian : requirements_debian_update_system()  49 > case ${__ret} in
++ /scripts/functions/requirements/debian : requirements_debian_update_system()  65 > rvm_error 'There has been an error while updating your system using `apt-get`.
It seems that there are some 404 Not Found errors for repositories listed in:

    /etc/apt/sources.list
    /etc/apt/sources.list.d/*.list

Make sure that all repositories are available from your system and verify your setup by running manually:

    sudo apt-get update

Make sure that it works correctly before proceeding with RVM.

If you are working from the GUI instead of the terminal, you might want to verify and fix broken
repositories using "Software & Updates" application.
'
++ /scripts/functions/logging : rvm_error()  168 > rvm_pretty_print stderr
++ /scripts/functions/logging : rvm_pretty_print()  88 > case "${rvm_pretty_print_flag:=auto}" in
++ /scripts/functions/logging : rvm_pretty_print()  94 > case "${TERM:-dumb}" in
++ /scripts/functions/logging : rvm_pretty_print()  98 > case "$1" in
++ /scripts/functions/logging : rvm_pretty_print()  100 > [[ -t 2 ]]
++ /scripts/functions/logging : rvm_pretty_print()  100 > return 1
++ /scripts/functions/logging : rvm_error()  170 > printf %b 'There has been an error while updating your system using `apt-get`.
It seems that there are some 404 Not Found errors for repositories listed in:

    /etc/apt/sources.list
    /etc/apt/sources.list.d/*.list

Make sure that all repositories are available from your system and verify your setup by running manually:

    sudo apt-get update

Make sure that it works correctly before proceeding with RVM.

If you are working from the GUI instead of the terminal, you might want to verify and fix broken
repositories using "Software & Updates" application.
\n'
++ /scripts/functions/requirements/debian : requirements_debian_update_system()  68 > return 100
